//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCtest20180709.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Linq.Expressions;

    public partial class user
    {
        [Key]
        public int user_id { get; set; }
        public string user_name { get; set; }
        public Nullable<int> dept_id { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }

        internal static object AsEnumerable() {
            throw new NotImplementedException();
        }

        public virtual dept dept { get; set; }
    }
}
